# 육상선수 종목별 기록 데이터

In [1]:
import numpy as np
A = np.array([
              [3.73, 1.86, 15.8, 4.05, 7.27, 45.66, 34.92 ],
              [3.57, 1.80, 16.23, 2.96, 6.71, 42.56, 37.31],
              [3.22, 1.83, 14.20, 3.51, 6.68, 44.54, 39.23],
              [2.81, 1.80, 15.23, 2.69, 6.25, 42.78, 31.19],
              [2.91, 1.74, 14.76, 2.68, 6.32, 47.46, 35.53],
              [2.67, 1.83, 13.50, 1.96, 6.33, 42.82, 37.64]
])

# 허들종목 (0번컬럼) 기록 데이터 통계지표

In [3]:
print('허들 종목 기록 데이터')
hurdles = A[:,0]
print(hurdles)
print(f'평균:{np.mean(hurdles):.3f}')
print(f'분산:{np.var(hurdles, ddof=1):.3f}') # ddof : 자유도
print(f'표편:{np.std(hurdles):.3f}')

허들 종목 기록 데이터
[3.73 3.57 3.22 2.81 2.91 2.67]
평균:3.152
분산:0.154


# 공분산 행렬

In [9]:
print('[Coveriance Matrix]')
# rowvar : True( 기본값 ) 행이 변수를 나타내며 열은 각 변수의 관측치를 나타낸다.
B = np.cov(A, rowvar=False)
print(np.round(B,2))
#print(B)

[Coveriance Matrix]
[[ 0.18  0.01  0.32  0.26  0.15  0.11  0.22]
 [ 0.01  0.   -0.    0.01  0.01 -0.03  0.02]
 [ 0.32 -0.    1.03  0.39  0.2  -0.03 -1.06]
 [ 0.26  0.01  0.39  0.53  0.24  0.52  0.08]
 [ 0.15  0.01  0.2   0.24  0.15  0.16  0.21]
 [ 0.11 -0.03 -0.03  0.52  0.16  3.88  0.09]
 [ 0.22  0.02 -1.06  0.08  0.21  0.09  7.87]]


In [10]:
col_mean = np.mean(A, axis=0)
A = A - col_mean
cov = np.matmul(A.T, A) / (len(A) - 1)
print(cov)

[[ 1.84256667e-01  7.36000000e-03  3.24893333e-01  2.61910000e-01
   1.51253333e-01  1.08713333e-01  2.22240000e-01]
 [ 7.36000000e-03  1.68000000e-03 -7.60000000e-04  1.35600000e-02
   1.03400000e-02 -2.90800000e-02  2.22600000e-02]
 [ 3.24893333e-01 -7.60000000e-04  1.02806667e+00  3.88260000e-01
   1.99426667e-01 -2.62533333e-02 -1.05972000e+00]
 [ 2.61910000e-01  1.35600000e-02  3.88260000e-01  5.28110000e-01
   2.43560000e-01  5.23940000e-01  7.84600000e-02]
 [ 1.51253333e-01  1.03400000e-02  1.99426667e-01  2.43560000e-01
   1.48186667e-01  1.57186667e-01  2.10000000e-01]
 [ 1.08713333e-01 -2.90800000e-02 -2.62533333e-02  5.23940000e-01
   1.57186667e-01  3.88422667e+00  8.52800000e-02]
 [ 2.22240000e-01  2.22600000e-02 -1.05972000e+00  7.84600000e-02
   2.10000000e-01  8.52800000e-02  7.87132000e+00]]
